name: AWS Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up AWS CLI
        run: |
          aws configure set aws_access_key_id YOUR_AWS_ACCESS_KEY
          aws configure set aws_secret_access_key YOUR_AWS_SECRET_KEY
          aws configure set region us-east-1
          
      - name: Deploy to AWS
        run: |
          aws s3 cp myapp.zip s3://mybucket/
