name: AWS Deployment

on:
  push:
    branches:
      - main  # Trigger the action when there is a push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use an Ubuntu-based runner

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Hardcode AWS credentials (NOT recommended)
      - name: Configure AWS credentials (Hardcoded)
        run: |
          aws configure set aws_access_key_id "AKIAEXAMPLE"  # Hardcoded AWS Access Key ID
          aws configure set aws_secret_access_key "SECRETEXAMPLE"  # Hardcoded AWS Secret Access Key
          aws configure set region "us-east-1"  # AWS Region (adjust as needed)

      # Step 3: Install AWS CLI
      - name: Install AWS CLI
        run: |
          sudo apt-get install awscli  # Install the AWS CLI on the runner

      # Step 4: Deploy to AWS (Example - Upload a file to S3)
      - name: Deploy to AWS S3
        run: |
          aws s3 cp myapp.zip s3://mybucket/  # Replace with actual command

      # Optional: Step to confirm success
      - name: Verify deployment
        run: |
          aws s3 ls s3://mybucket/  # List files in the S3 bucket to confirm the upload
