name: Secret Scanning
 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
jobs:
  scan-secrets:
    name: Scan for Secrets
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
 
      - name: Run TruffleHog to Scan for Secrets
        uses: edplato/trufflehog-actions-scan@v0.11
        with:
          scanArguments: "--regex --entropy=True"
