name: GitHub Secret Scanning
 
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
 
jobs:
  scan-secrets:
    name: Run GitHub Secret Scanning
    runs-on: windows-latest
 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
 
      - name: Enable GitHub Secret Scanning
        run: |
          echo "GitHub's built-in secret scanning will detect secrets in your repo."
