name: Secret Scanning
 
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
 
jobs:
  scan-secrets:
    name: Scan for Secrets
    runs-on: windows-latest
 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
 
      - name: Run TruffleHog to Scan for Secrets
        uses: edplato/trufflehog-actions-scan@v0.9
        with:
          scanArguments: "--regex --entropy=True"
